export const MFA_ERROR_CODES = {
  MFA_NOT_ENABLED: 'MFA_NOT_ENABLED',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  MFA_SETUP_NOT_INITIATED: 'MFA_SETUP_NOT_INITIATED',
  INVALID_MFA_CODE: 'INVALID_MFA_CODE',
  INVALID_BACKUP_CODE: 'INVALID_BACKUP_CODE',
  MFA_CHALLENGE_NOT_FOUND: 'MFA_CHALLENGE_NOT_FOUND',
  MFA_CHALLENGE_EXPIRED: 'MFA_CHALLENGE_EXPIRED',
  MFA_CHALLENGE_USED: 'MFA_CHALLENGE_USED',
  MFA_TOO_MANY_ATTEMPTS: 'MFA_TOO_MANY_ATTEMPTS',
  MFA_REQUIRED_BY_ORG: 'MFA_REQUIRED_BY_ORG',
  MFA_METHOD_NOT_ALLOWED: 'MFA_METHOD_NOT_ALLOWED',
} as const;

export const MFA_CONSTANTS = {
  TOTP_SECRET_BYTES: 20,
  TOTP_DIGITS: 6,
  TOTP_STEP_SECONDS: 30,
  BACKUP_CODE_BYTES: 6,
  BACKUP_CODE_GROUP_SIZE: 4,
  MAX_CHALLENGE_ATTEMPTS: 5,
} as const;
