export const ORG_ERROR_CODES = {
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_SLUG_TAKEN: 'ORG_SLUG_TAKEN',
  ORG_DELETED: 'ORG_DELETED',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_EXISTS: 'MEMBERSHIP_EXISTS',
  LAST_ADMIN_REMOVAL: 'LAST_ADMIN_REMOVAL',
  CROSS_TENANT_ACCESS: 'CROSS_TENANT_ACCESS',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EMAIL_MISMATCH: 'INVITATION_EMAIL_MISMATCH',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_REVOKED: 'INVITATION_REVOKED',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_INVALID_TOKEN: 'INVITATION_INVALID_TOKEN',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
} as const;

export const SYSTEM_ROLE_SLUGS = {
  SUPER_ADMIN: 'super-admin',
  ADMIN: 'admin',
  MANAGER: 'manager',
  USER: 'user',
} as const;

export const INVITATION_TTL_MS = 7 * 24 * 60 * 60 * 1000;
