export const OAUTH_ERROR_CODES = {
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',
  OAUTH_STATE_EXPIRED: 'OAUTH_STATE_EXPIRED',
  OAUTH_PROVIDER_NOT_CONFIGURED: 'OAUTH_PROVIDER_NOT_CONFIGURED',
  OAUTH_EMAIL_MISMATCH: 'OAUTH_EMAIL_MISMATCH',
  OAUTH_ACCOUNT_ALREADY_LINKED: 'OAUTH_ACCOUNT_ALREADY_LINKED',
  OAUTH_LINK_FORBIDDEN: 'OAUTH_LINK_FORBIDDEN',
  OAUTH_LAST_AUTH_METHOD: 'OAUTH_LAST_AUTH_METHOD',
  OAUTH_PROFILE_INCOMPLETE: 'OAUTH_PROFILE_INCOMPLETE',
} as const;

export const OAUTH_CACHE_KEYS = {
  state: (state: string) => `oauth:state:${state}`,
  pkce: (state: string) => `oauth:pkce:${state}`,
};

export const OAUTH_STATE_BYTES = 32;
export const OAUTH_PKCE_VERIFIER_BYTES = 32;
