export const AUTH_STRATEGIES = {
  JWT: 'jwt',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  PASSWORD_RECENTLY_USED: 'PASSWORD_RECENTLY_USED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  TOKEN_VERSION_MISMATCH: 'TOKEN_VERSION_MISMATCH',
} as const;

export const AUTH_CACHE_KEYS = {
  blocklist: (tokenJti: string) => `auth:blocklist:${tokenJti}`,
  session: (sessionId: string) => `auth:session:${sessionId}`,
  userSessions: (userId: string) => `auth:user:${userId}:sessions`,
};

export const REFRESH_TOKEN_BYTES = 48;
export const VERIFICATION_TOKEN_BYTES = 32;
export const RESET_TOKEN_BYTES = 32;
